apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apidescriptions.apigee.dev
spec:
  group: apigee.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                parent:
                  type: string
            status:
              type: object
              properties:
                message:
                  type: string
      subresources:
        status: {}
  names:
    kind: ApiDescription
    plural: apidescriptions
  scope: Namespaced
